// <auto-generated />
namespace TrainingWebAPI.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initdata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initdata));
        
        string IMigrationMetadata.Id
        {
            get { return "201911240640047_init-data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
